// <auto-generated />
using System;
using AccessService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AccessServiceDbContext))]
    [Migration("20260429112921_AddAccessSchema")]
    partial class AddAccessSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessService.Domain.InviteLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<bool>("MultiUse")
                        .HasColumnType("boolean")
                        .HasColumnName("multi_use");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_invite_links_plan_id");

                    b.ToTable("invite_links", "access");
                });

            modelBuilder.Entity("AccessService.Domain.InviteRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InviteLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("invite_link_id");

                    b.Property<string>("IpHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ip_hash");

                    b.Property<Guid>("PlanGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_grant_id");

                    b.Property<DateTimeOffset>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("InviteLinkId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_invite_redemptions_invite_user");

                    b.ToTable("invite_redemptions", "access");
                });

            modelBuilder.Entity("AccessService.Domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<Guid[]>("CourseIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("course_ids");

                    b.Property<Guid?>("CoverFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_file_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("features");

                    b.Property<bool>("IncludesFutureContent")
                        .HasColumnType("boolean")
                        .HasColumnName("includes_future_content");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("long_description");

                    b.Property<int?>("PriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_cents");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.HasKey("Id");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("ix_plans_is_public")
                        .HasFilter("is_active");

                    b.ToTable("plans", "access");
                });

            modelBuilder.Entity("AccessService.Domain.PlanGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceRef")
                        .HasColumnType("uuid")
                        .HasColumnName("source_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_plan_grants_plan_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_plan_grants_user_status");

                    b.ToTable("plan_grants", "access");
                });

            modelBuilder.Entity("AccessService.Domain.InviteLink", b =>
                {
                    b.OwnsOne("AccessService.Domain.InviteToken", "Token", b1 =>
                        {
                            b1.Property<Guid>("InviteLinkId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(22)
                                .HasColumnType("character varying(22)")
                                .HasColumnName("token");

                            b1.HasKey("InviteLinkId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_invite_links_token");

                            b1.ToTable("invite_links", "access");

                            b1.WithOwner()
                                .HasForeignKey("InviteLinkId");
                        });

                    b.Navigation("Token")
                        .IsRequired();
                });

            modelBuilder.Entity("AccessService.Domain.Plan", b =>
                {
                    b.OwnsOne("AccessService.Domain.PlanCapabilities", "Capabilities", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Profile")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("capability_profile");

                            b1.HasKey("PlanId");

                            b1.ToTable("plans", "access");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsOne("AccessService.Domain.PlanDisplayName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.HasKey("PlanId");

                            b1.ToTable("plans", "access");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsOne("AccessService.Domain.PlanSlug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("slug");

                            b1.HasKey("PlanId");

                            b1.ToTable("plans", "access");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsOne("AccessService.Domain.PlanTerm", "Term", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("term_kind");

                            b1.Property<int?>("RecurringIntervalDays")
                                .HasColumnType("integer")
                                .HasColumnName("term_recurring_days");

                            b1.HasKey("PlanId");

                            b1.ToTable("plans", "access");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.Navigation("Capabilities")
                        .IsRequired();

                    b.Navigation("DisplayName")
                        .IsRequired();

                    b.Navigation("Slug")
                        .IsRequired();

                    b.Navigation("Term")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
