// <auto-generated />
using System;
using AccessService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AccessServiceDbContext))]
    [Migration("20260617162437_AddPlanGrantUpgradeBasePrice")]
    partial class AddPlanGrantUpgradeBasePrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessService.Core.Domain.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("response_body");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Key");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_idempotency_keys_created");

                    b.ToTable("idempotency_keys", "access");
                });

            modelBuilder.Entity("AccessService.Domain.Billing.BillingConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("billing_config", "access");
                });

            modelBuilder.Entity("AccessService.Domain.HomePins.PlanPinnedMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sort_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "MaterialId")
                        .IsUnique()
                        .HasDatabaseName("uq_plan_pinned_materials_plan_material");

                    b.HasIndex("PlanId", "SortKey")
                        .HasDatabaseName("ix_plan_pinned_materials_plan_sort");

                    b.ToTable("plan_pinned_materials", "access");
                });

            modelBuilder.Entity("AccessService.Domain.Integrations.GitHub.AuthorGithubInstallation", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<string>("OrgLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_login");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.HasKey("AuthorId");

                    b.HasIndex("InstallationId")
                        .IsUnique()
                        .HasDatabaseName("ix_author_github_installations_installation_id");

                    b.HasIndex("OrgLogin")
                        .HasDatabaseName("ix_author_github_installations_org_login");

                    b.ToTable("author_github_installations", "access");
                });

            modelBuilder.Entity("AccessService.Domain.Integrations.GitHub.GithubOrgInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<long?>("GithubInvitationId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_invitation_id");

                    b.Property<string>("GithubLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("github_login");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("OrgLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_login");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrgLogin", "GithubLogin")
                        .HasDatabaseName("ix_github_org_invitations_pending");

                    b.HasIndex("PlanId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_github_org_invitations_user_plan");

                    b.ToTable("github_org_invitations", "access");
                });

            modelBuilder.Entity("AccessService.Domain.InviteLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<bool>("MultiUse")
                        .HasColumnType("boolean")
                        .HasColumnName("multi_use");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_invite_links_plan_id");

                    b.ToTable("invite_links", "access");
                });

            modelBuilder.Entity("AccessService.Domain.InviteRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InviteLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("invite_link_id");

                    b.Property<string>("IpHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ip_hash");

                    b.Property<Guid>("PlanGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_grant_id");

                    b.Property<DateTimeOffset>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("InviteLinkId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_invite_redemptions_invite_user");

                    b.ToTable("invite_redemptions", "access");
                });

            modelBuilder.Entity("AccessService.Domain.Onboarding.PlanOnboardingFlow", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlanId");

                    b.ToTable("plan_onboarding_flows", "access");
                });

            modelBuilder.Entity("AccessService.Domain.Onboarding.PlanOnboardingStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSkippable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_skippable");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("SortOrder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("step_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "SortOrder")
                        .HasDatabaseName("ix_plan_onboarding_steps_plan_order");

                    b.ToTable("plan_onboarding_steps", "access");
                });

            modelBuilder.Entity("AccessService.Domain.Onboarding.UserPlanOnboarding", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid[]>("CompletedStepIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("completed_step_ids");

                    b.Property<Guid?>("CurrentStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_step_id");

                    b.Property<Guid[]>("SkippedStepIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("skipped_step_ids");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("UserId", "PlanId");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("ix_user_plan_onboardings_user_pending")
                        .HasFilter("completed_at IS NULL");

                    b.ToTable("user_plan_onboardings", "access");
                });

            modelBuilder.Entity("AccessService.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("ExternalProviderRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_provider_ref");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_orders_correlation_id")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.HasIndex("ExternalProviderRef")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_external_provider_ref")
                        .HasFilter("external_provider_ref IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orders_user_id");

                    b.ToTable("orders", "access");
                });

            modelBuilder.Entity("AccessService.Domain.OrderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("ix_order_events_order_id_created");

                    b.ToTable("order_events", "access");
                });

            modelBuilder.Entity("AccessService.Domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<int>("Capabilities")
                        .HasColumnType("integer")
                        .HasColumnName("capabilities");

                    b.Property<Guid?>("CoverFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_file_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DiscountEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discount_ends_at");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percent");

                    b.Property<DateTimeOffset?>("DiscountStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discount_starts_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("features");

                    b.Property<string>("GitHubOrg")
                        .HasMaxLength(39)
                        .HasColumnType("character varying(39)")
                        .HasColumnName("github_org_slug");

                    b.Property<bool>("IncludesFutureContent")
                        .HasColumnType("boolean")
                        .HasColumnName("includes_future_content");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_highlighted");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("long_description");

                    b.Property<string>("OfferType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("offer_type");

                    b.Property<long?>("PriceCents")
                        .HasColumnType("bigint")
                        .HasColumnName("price_cents");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("TelegramWelcomeMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("telegram_welcome_message");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tier");

                    b.Property<int?>("TrialDurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("trial_duration_days");

                    b.HasKey("Id");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("ix_plans_is_public")
                        .HasFilter("is_active");

                    b.ToTable("plans", "access");
                });

            modelBuilder.Entity("AccessService.Domain.PlanCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_plan_courses_course_id");

                    b.HasIndex("PlanId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("ux_plan_courses_plan_course");

                    b.ToTable("plan_courses", "access");
                });

            modelBuilder.Entity("AccessService.Domain.PlanGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreditOverrideUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("credit_override_until");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("ExpiryReminderSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_reminder_sent_at");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<long?>("PricePaidCents")
                        .HasColumnType("bigint")
                        .HasColumnName("price_paid_cents");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceRef")
                        .HasColumnType("uuid")
                        .HasColumnName("source_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<long?>("UpgradeBasePriceCents")
                        .HasColumnType("bigint")
                        .HasColumnName("upgrade_base_price_cents");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_plan_grants_plan_id");

                    b.HasIndex("UserId", "PlanId")
                        .IsUnique()
                        .HasDatabaseName("uq_plan_grants_user_plan_active")
                        .HasFilter("status = 'ACTIVE'");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_plan_grants_user_status");

                    b.ToTable("plan_grants", "access");
                });

            modelBuilder.Entity("AccessService.Domain.InviteLink", b =>
                {
                    b.OwnsOne("AccessService.Domain.InviteToken", "Token", b1 =>
                        {
                            b1.Property<Guid>("InviteLinkId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(22)
                                .HasColumnType("character varying(22)")
                                .HasColumnName("token");

                            b1.HasKey("InviteLinkId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_invite_links_token");

                            b1.ToTable("invite_links", "access");

                            b1.WithOwner()
                                .HasForeignKey("InviteLinkId");
                        });

                    b.Navigation("Token")
                        .IsRequired();
                });

            modelBuilder.Entity("AccessService.Domain.Onboarding.PlanOnboardingFlow", b =>
                {
                    b.HasOne("AccessService.Domain.Plan", null)
                        .WithOne()
                        .HasForeignKey("AccessService.Domain.Onboarding.PlanOnboardingFlow", "PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessService.Domain.Onboarding.PlanOnboardingStep", b =>
                {
                    b.HasOne("AccessService.Domain.Onboarding.PlanOnboardingFlow", null)
                        .WithMany("Steps")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessService.Domain.OrderEvent", b =>
                {
                    b.HasOne("AccessService.Domain.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessService.Domain.Plan", b =>
                {
                    b.OwnsOne("AccessService.Domain.PlanDisplayName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.HasKey("PlanId");

                            b1.ToTable("plans", "access");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsOne("AccessService.Domain.PlanSlug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("slug");

                            b1.HasKey("PlanId");

                            b1.ToTable("plans", "access");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.OwnsOne("AccessService.Domain.PlanTerm", "Term", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("term_kind");

                            b1.Property<int?>("RecurringIntervalDays")
                                .HasColumnType("integer")
                                .HasColumnName("term_recurring_days");

                            b1.HasKey("PlanId");

                            b1.ToTable("plans", "access");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.Navigation("DisplayName")
                        .IsRequired();

                    b.Navigation("Slug")
                        .IsRequired();

                    b.Navigation("Term")
                        .IsRequired();
                });

            modelBuilder.Entity("AccessService.Domain.PlanCourse", b =>
                {
                    b.HasOne("AccessService.Domain.Plan", null)
                        .WithMany("Courses")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessService.Domain.Onboarding.PlanOnboardingFlow", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("AccessService.Domain.Plan", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
