<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
        <PackageReference Include="Scalar.AspNetCore" />
        <ProjectReference Include="..\..\..\Shared\Framework\Framework.csproj" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Observability\Observability.csproj" />
      <ProjectReference Include="..\..\..\Shared\Authentication\Authentication.csproj" />
      <ProjectReference Include="..\..\..\Shared\PlatformBootstrap\PlatformBootstrap.csproj" />
      <ProjectReference Include="..\TagService.Contracts\TagService.Contracts.csproj" />
      <ProjectReference Include="..\TagService.Core\TagService.Core.csproj" />
      <ProjectReference Include="..\TagService.Domain\TagService.Domain.csproj" />
      <ProjectReference Include="..\TagService.Infrastructure.Postgres\TagService.Infrastructure.Postgres.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\..\Shared\Observability\serilog*.json"
               CopyToOutputDirectory="PreserveNewest"
               CopyToPublishDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
