<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\DomainEvents\DomainEvents.csproj" />
    <ProjectReference Include="..\..\..\Shared\Messaging\RabbitMqMessaging\RabbitMqMessaging.csproj" />
    <ProjectReference Include="..\MaterialProcessingService.Contracts\MaterialProcessingService.Contracts.csproj" />
    <ProjectReference Include="..\MaterialProcessingService.Core\MaterialProcessingService.Core.csproj" />
    <ProjectReference Include="..\MaterialProcessingService.Domain\MaterialProcessingService.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
  </ItemGroup>
</Project>
