<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="EducationContentService.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <ProjectReference Include="..\..\..\Shared\Core\Core.csproj" />
    <PackageReference Include="Scrutor" />
    <ProjectReference Include="..\..\..\Shared\SharedKernel\SharedKernel.csproj" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Authentication\Authentication.csproj" />
    <ProjectReference Include="..\..\..\Shared\Common\Common.csproj" />
  </ItemGroup>

</Project>
