// <auto-generated />
using System;
using AssignmentReviewService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssignmentReviewService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AssignmentReviewServiceDbContext))]
    [Migration("20260706143428_AddStudentPrMessages")]
    partial class AddStudentPrMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assignment_review")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssignmentReviewService.Domain.AiSettings.AiModelSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ReviewEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("review_enabled");

                    b.Property<string>("ReviewerBasePrompt")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("reviewer_base_prompt");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.ToTable("ai_model_settings", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.AiReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_at");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<int>("IterationsCount")
                        .HasColumnType("integer")
                        .HasColumnName("iterations_count");

                    b.Property<Guid?>("LatestIterationId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_iteration_id");

                    b.Property<string>("LatestVerdict")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("latest_verdict");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<int>("PullNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pull_number");

                    b.Property<string>("PullRequestUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pull_request_url");

                    b.Property<string>("RepoFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("repo_full_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("uq_ai_reviews_submission");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_reviews_user_id");

                    b.ToTable("ai_reviews", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.AiReviewIteration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_review_id");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<long?>("GitHubReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_review_id");

                    b.Property<int>("InlineCommentsCount")
                        .HasColumnType("integer")
                        .HasColumnName("inline_comments_count");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<int>("IterationNumber")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_number");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_used");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Verdict")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("verdict");

                    b.HasKey("Id");

                    b.HasIndex("AiReviewId", "IterationNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_ai_review_iterations_review_number");

                    b.ToTable("ai_review_iterations", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.AiReviewIterationFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsHelpful")
                        .HasColumnType("boolean")
                        .HasColumnName("is_helpful");

                    b.Property<Guid>("IterationId")
                        .HasColumnType("uuid")
                        .HasColumnName("iteration_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IterationId")
                        .HasDatabaseName("ix_ai_review_iteration_feedback_iteration");

                    b.HasIndex("IterationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_ai_review_iteration_feedback_iteration_user");

                    b.ToTable("ai_review_iteration_feedback", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.IssueReviewSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorPrompt")
                        .HasColumnType("text")
                        .HasColumnName("author_prompt");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ReviewAspects")
                        .HasColumnType("text")
                        .HasColumnName("review_aspects");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique()
                        .HasDatabaseName("uq_issue_review_specs_issue");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_issue_review_specs_project");

                    b.ToTable("issue_review_specs", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.ProjectReviewGuidelines", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("GuidelinesMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guidelines_markdown");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("uq_project_review_guidelines_project");

                    b.ToTable("project_review_guidelines", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.StudentPrMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_review_id");

                    b.Property<string>("AnswerBody")
                        .HasColumnType("text")
                        .HasColumnName("answer_body");

                    b.Property<long?>("AnswerGitHubCommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("answer_github_comment_id");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<string>("AuthorGithubLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("author_github_login");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("CommentUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment_url");

                    b.Property<DateTimeOffset>("CreatedAtGithub")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_github");

                    b.Property<long>("GitHubCommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_comment_id");

                    b.Property<long?>("InReplyToGitHubId")
                        .HasColumnType("bigint")
                        .HasColumnName("in_reply_to_github_id");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<int?>("Line")
                        .HasColumnType("integer")
                        .HasColumnName("line");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("AiReviewId")
                        .HasDatabaseName("ix_student_pr_messages_ai_review_id");

                    b.HasIndex("GitHubCommentId")
                        .IsUnique()
                        .HasDatabaseName("uq_student_pr_messages_github_comment_id");

                    b.ToTable("student_pr_messages", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Vcs.VcsInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_user_id");

                    b.Property<string>("OwnerExternalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("owner_external_id");

                    b.Property<string>("OwnerLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_login");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("owner_type");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("RepoSelections")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("repo_selections");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LinkedUserId")
                        .HasDatabaseName("ix_vcs_installations_linked_user_id");

                    b.HasIndex("Provider", "InstallationId")
                        .IsUnique()
                        .HasDatabaseName("uq_vcs_installations_provider_installation");

                    b.ToTable("vcs_installations", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.AiSettings.AiModelSettings", b =>
                {
                    b.OwnsOne("AssignmentReviewService.Domain.AiSettings.AiModelSlot", "Reviewer", b1 =>
                        {
                            b1.Property<Guid>("AiModelSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MaxOutputTokens")
                                .HasColumnType("integer")
                                .HasColumnName("reviewer_max_output_tokens");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("reviewer_model");

                            b1.Property<double?>("Temperature")
                                .HasColumnType("double precision")
                                .HasColumnName("reviewer_temperature");

                            b1.Property<int?>("TimeoutSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("reviewer_timeout_seconds");

                            b1.HasKey("AiModelSettingsId");

                            b1.ToTable("ai_model_settings", "assignment_review");

                            b1.WithOwner()
                                .HasForeignKey("AiModelSettingsId");
                        });

                    b.Navigation("Reviewer")
                        .IsRequired();
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.AiReviewIteration", b =>
                {
                    b.HasOne("AssignmentReviewService.Domain.Reviews.AiReview", null)
                        .WithMany("Iterations")
                        .HasForeignKey("AiReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.StudentPrMessage", b =>
                {
                    b.HasOne("AssignmentReviewService.Domain.Reviews.AiReview", null)
                        .WithMany()
                        .HasForeignKey("AiReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.AiReview", b =>
                {
                    b.Navigation("Iterations");
                });
#pragma warning restore 612, 618
        }
    }
}
