// <auto-generated />
using System;
using AssignmentReviewService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssignmentReviewService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AssignmentReviewServiceDbContext))]
    [Migration("20260510174427_AddReviewSpecsAndGuidelines")]
    partial class AddReviewSpecsAndGuidelines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assignment_review")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssignmentReviewService.Domain.AiSettings.AiModelSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.ToTable("ai_model_settings", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Context.ContextChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("embedding_model");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_context_chunks_document_id");

                    b.ToTable("context_chunks", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Context.ContextDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("owner_type");

                    b.Property<int>("RawContentSize")
                        .HasColumnType("integer")
                        .HasColumnName("raw_content_size");

                    b.Property<string>("RepoBranch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("repo_branch");

                    b.Property<string>("RepoCommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("repo_commit_sha");

                    b.Property<string>("RepoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("repo_url");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId")
                        .HasDatabaseName("ix_context_documents_owner");

                    b.ToTable("context_documents", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.AiReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<int>("IterationsCount")
                        .HasColumnType("integer")
                        .HasColumnName("iterations_count");

                    b.Property<Guid?>("LatestIterationId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_iteration_id");

                    b.Property<string>("LatestVerdict")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("latest_verdict");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<int>("PullNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pull_number");

                    b.Property<string>("PullRequestUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pull_request_url");

                    b.Property<string>("RepoFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("repo_full_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("uq_ai_reviews_submission");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_reviews_user_id");

                    b.ToTable("ai_reviews", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.AiReviewIteration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_review_id");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<long?>("GitHubReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_review_id");

                    b.Property<int>("InlineCommentsCount")
                        .HasColumnType("integer")
                        .HasColumnName("inline_comments_count");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<int>("IterationNumber")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_number");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_used");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("UsedChunkIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("used_chunk_ids");

                    b.Property<string>("Verdict")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("verdict");

                    b.HasKey("Id");

                    b.HasIndex("AiReviewId", "IterationNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_ai_review_iterations_review_number");

                    b.ToTable("ai_review_iterations", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.IssueReviewSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorPrompt")
                        .HasColumnType("text")
                        .HasColumnName("author_prompt");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ReferenceLinks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reference_links");

                    b.Property<string>("ReviewAspects")
                        .HasColumnType("text")
                        .HasColumnName("review_aspects");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique()
                        .HasDatabaseName("uq_issue_review_specs_issue");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_issue_review_specs_project");

                    b.ToTable("issue_review_specs", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.ProjectReviewGuidelines", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("GuidelinesMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guidelines_markdown");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("uq_project_review_guidelines_project");

                    b.ToTable("project_review_guidelines", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Vcs.VcsInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_user_id");

                    b.Property<string>("OwnerExternalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("owner_external_id");

                    b.Property<string>("OwnerLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_login");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("owner_type");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("RepoSelections")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("repo_selections");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LinkedUserId")
                        .HasDatabaseName("ix_vcs_installations_linked_user_id");

                    b.HasIndex("Provider", "InstallationId")
                        .IsUnique()
                        .HasDatabaseName("uq_vcs_installations_provider_installation");

                    b.ToTable("vcs_installations", "assignment_review");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.AiSettings.AiModelSettings", b =>
                {
                    b.OwnsOne("AssignmentReviewService.Domain.AiSettings.AiModelSlot", "Embeddings", b1 =>
                        {
                            b1.Property<Guid>("AiModelSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MaxOutputTokens")
                                .HasColumnType("integer")
                                .HasColumnName("embeddings_max_output_tokens");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("embeddings_model");

                            b1.Property<double?>("Temperature")
                                .HasColumnType("double precision")
                                .HasColumnName("embeddings_temperature");

                            b1.Property<int?>("TimeoutSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("embeddings_timeout_seconds");

                            b1.HasKey("AiModelSettingsId");

                            b1.ToTable("ai_model_settings", "assignment_review");

                            b1.WithOwner()
                                .HasForeignKey("AiModelSettingsId");
                        });

                    b.OwnsOne("AssignmentReviewService.Domain.AiSettings.AiModelSlot", "Reviewer", b1 =>
                        {
                            b1.Property<Guid>("AiModelSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MaxOutputTokens")
                                .HasColumnType("integer")
                                .HasColumnName("reviewer_max_output_tokens");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("reviewer_model");

                            b1.Property<double?>("Temperature")
                                .HasColumnType("double precision")
                                .HasColumnName("reviewer_temperature");

                            b1.Property<int?>("TimeoutSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("reviewer_timeout_seconds");

                            b1.HasKey("AiModelSettingsId");

                            b1.ToTable("ai_model_settings", "assignment_review");

                            b1.WithOwner()
                                .HasForeignKey("AiModelSettingsId");
                        });

                    b.OwnsOne("AssignmentReviewService.Domain.AiSettings.AiModelSlot", "Triage", b1 =>
                        {
                            b1.Property<Guid>("AiModelSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MaxOutputTokens")
                                .HasColumnType("integer")
                                .HasColumnName("triage_max_output_tokens");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("triage_model");

                            b1.Property<double?>("Temperature")
                                .HasColumnType("double precision")
                                .HasColumnName("triage_temperature");

                            b1.Property<int?>("TimeoutSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("triage_timeout_seconds");

                            b1.HasKey("AiModelSettingsId");

                            b1.ToTable("ai_model_settings", "assignment_review");

                            b1.WithOwner()
                                .HasForeignKey("AiModelSettingsId");
                        });

                    b.Navigation("Embeddings")
                        .IsRequired();

                    b.Navigation("Reviewer")
                        .IsRequired();

                    b.Navigation("Triage")
                        .IsRequired();
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Context.ContextChunk", b =>
                {
                    b.HasOne("AssignmentReviewService.Domain.Context.ContextDocument", null)
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.AiReviewIteration", b =>
                {
                    b.HasOne("AssignmentReviewService.Domain.Reviews.AiReview", null)
                        .WithMany("Iterations")
                        .HasForeignKey("AiReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Context.ContextDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("AssignmentReviewService.Domain.Reviews.AiReview", b =>
                {
                    b.Navigation("Iterations");
                });
#pragma warning restore 612, 618
        }
    }
}
