<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions"/>
    <PackageReference Include="Microsoft.Extensions.Http"/>
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>    <ProjectReference Include="..\..\..\Shared\Core\Core.csproj" />
    <ProjectReference Include="..\..\..\Shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Authentication\Authentication.csproj"/>
  </ItemGroup>

</Project>
