<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions"/>    <ProjectReference Include="..\..\..\Shared\SharedKernel\SharedKernel.csproj" />
    <ProjectReference Include="../../../Shared/Ordering/Ordering/Ordering.csproj" />
  </ItemGroup>
</Project>
