<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TagService.Core\TagService.Core.csproj" />
    <ProjectReference Include="..\TagService.Domain\TagService.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Database\Database.csproj" />
  </ItemGroup>
</Project>
