<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\EducationContentService.Core\EducationContentService.Core.csproj"/>
    <ProjectReference Include="..\EducationContentService.Domain\EducationContentService.Domain.csproj"/>
    <ProjectReference Include="..\..\..\Shared\DomainEvents\DomainEvents.csproj"/>
    <ProjectReference Include="..\..\..\Shared\Database\Database.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    <PackageReference Include="WolverineFx.EntityFrameworkCore"/>
  </ItemGroup>
</Project>
