<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NotificationService.Core\NotificationService.Core.csproj" />
    <ProjectReference Include="..\NotificationService.Domain\NotificationService.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Database\Database.csproj" />
  </ItemGroup>
</Project>
