<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
        <PackageReference Include="Npgsql" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <ProjectReference Include="..\..\..\Shared\Framework\Framework.csproj" />
        <PackageReference Include="Scalar.AspNetCore" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Authentication\Authentication.csproj" />
      <ProjectReference Include="..\..\..\Shared\ContentAccess\ContentAccess.Redis\ContentAccess.Redis.csproj" />
      <ProjectReference Include="..\..\..\Shared\Observability\Observability.csproj" />
      <ProjectReference Include="..\..\..\Shared\PlatformBootstrap\PlatformBootstrap.csproj" />
      <ProjectReference Include="..\CommentService.Contracts\CommentService.Contracts.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Content Include="..\..\..\Shared\Observability\serilog*.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
      <ProjectReference Include="..\CommentService.Core\CommentService.Core.csproj" />
      <ProjectReference Include="..\CommentService.Domain\CommentService.Domain.csproj" />
      <ProjectReference Include="..\CommentService.Infrastructure.Postgres\CommentService.Infrastructure.Postgres.csproj" />
    </ItemGroup>

</Project>
