<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <ProjectReference Include="..\..\..\Shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>
</Project>
