<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" />
    <ProjectReference Include="..\..\..\Shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\DomainEvents\DomainEvents.csproj" />
    <ProjectReference Include="..\..\..\Shared\Ordering\Ordering\Ordering.csproj" />
  </ItemGroup>

</Project>
