// <auto-generated />
using System;
using MaterialProcessingService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaterialProcessingService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(MaterialProcessingServiceDbContext))]
    [Migration("20260712004856_AddStuckJobHeartbeatIndexes")]
    partial class AddStuckJobHeartbeatIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("material_processing")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaterialProcessingService.Domain.AiSettings.AiModelSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoProcessVideosEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_process_videos_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.ToTable("ai_model_settings", "material_processing");
                });

            modelBuilder.Entity("MaterialProcessingService.Domain.ContentDrafts.ContentGenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetVersion")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_version");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("ModelOverride")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_override");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stage");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_content_jobs_status_updated_at");

                    b.HasIndex("VideoAssetId", "MaterialId")
                        .IsUnique()
                        .HasDatabaseName("ux_content_jobs_video_material_active")
                        .HasFilter("status IN ('QUEUED', 'PROCESSING')");

                    b.HasIndex("VideoAssetId", "MaterialId", "Status")
                        .HasDatabaseName("ix_content_jobs_video_material_status");

                    b.ToTable("content_generation_jobs", "material_processing");
                });

            modelBuilder.Entity("MaterialProcessingService.Domain.Timecodes.TimecodeGenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetVersion")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_version");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<string>("ModelOverride")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_override");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stage");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger_source");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("VideoAssetId")
                        .IsUnique()
                        .HasDatabaseName("ux_timecode_jobs_video_active")
                        .HasFilter("status IN ('QUEUED', 'PROCESSING')");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_timecode_jobs_status_updated_at");

                    b.HasIndex("VideoAssetId", "Status")
                        .HasDatabaseName("ix_timecode_jobs_video_status");

                    b.ToTable("timecode_generation_jobs", "material_processing");
                });

            modelBuilder.Entity("MaterialProcessingService.Domain.Transcripts.VideoTranscript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetVersion")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_version");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<string>("Segments")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("segments_json");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("VideoAssetId", "AssetVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_video_transcripts_video_asset_version");

                    b.ToTable("video_transcripts", "material_processing");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("wolverine_incoming_envelopes", "material_processing", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("wolverine_outgoing_envelopes", "material_processing", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MaterialProcessingService.Domain.AiSettings.AiModelSettings", b =>
                {
                    b.OwnsOne("MaterialProcessingService.Domain.AiSettings.AiModelSlot", "ContentGeneration", b1 =>
                        {
                            b1.Property<Guid>("AiModelSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MaxOutputTokens")
                                .HasColumnType("integer")
                                .HasColumnName("content_max_output_tokens");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_model");

                            b1.Property<double?>("Temperature")
                                .HasColumnType("double precision")
                                .HasColumnName("content_temperature");

                            b1.Property<int?>("TimeoutSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("content_timeout_seconds");

                            b1.HasKey("AiModelSettingsId");

                            b1.ToTable("ai_model_settings", "material_processing");

                            b1.WithOwner()
                                .HasForeignKey("AiModelSettingsId");
                        });

                    b.OwnsOne("MaterialProcessingService.Domain.AiSettings.AiModelSlot", "SpeechToText", b1 =>
                        {
                            b1.Property<Guid>("AiModelSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MaxOutputTokens")
                                .HasColumnType("integer")
                                .HasColumnName("stt_max_output_tokens");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("stt_model");

                            b1.Property<double?>("Temperature")
                                .HasColumnType("double precision")
                                .HasColumnName("stt_temperature");

                            b1.Property<int?>("TimeoutSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("stt_timeout_seconds");

                            b1.HasKey("AiModelSettingsId");

                            b1.ToTable("ai_model_settings", "material_processing");

                            b1.WithOwner()
                                .HasForeignKey("AiModelSettingsId");
                        });

                    b.OwnsOne("MaterialProcessingService.Domain.AiSettings.AiModelSlot", "TimecodeGeneration", b1 =>
                        {
                            b1.Property<Guid>("AiModelSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MaxOutputTokens")
                                .HasColumnType("integer")
                                .HasColumnName("timecode_max_output_tokens");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("timecode_model");

                            b1.Property<double?>("Temperature")
                                .HasColumnType("double precision")
                                .HasColumnName("timecode_temperature");

                            b1.Property<int?>("TimeoutSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("timecode_timeout_seconds");

                            b1.HasKey("AiModelSettingsId");

                            b1.ToTable("ai_model_settings", "material_processing");

                            b1.WithOwner()
                                .HasForeignKey("AiModelSettingsId");
                        });

                    b.Navigation("ContentGeneration")
                        .IsRequired();

                    b.Navigation("SpeechToText")
                        .IsRequired();

                    b.Navigation("TimecodeGeneration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
