<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
  </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SearchService.Core\SearchService.Core.csproj" />
      <ProjectReference Include="..\SearchService.Domain\SearchService.Domain.csproj" />
      <ProjectReference Include="..\..\..\Shared\Database\Database.csproj" />
    </ItemGroup>

</Project>
