<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions"/>
    <ProjectReference Include="..\..\..\Shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Common\Common.csproj" />
    <ProjectReference Include="..\..\..\Shared\DomainEvents\DomainEvents.csproj" />
  </ItemGroup>
</Project>
