<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Core\Core.csproj" />
    <ProjectReference Include="..\..\..\Shared\Framework\Framework.csproj" />
    <PackageReference Include="Typesense" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore"/>
    <PackageReference Include="WolverineFx.RabbitMQ"/>
    <PackageReference Include="WolverineFx.Postgresql"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Authentication\Authentication.csproj" />
    <ProjectReference Include="..\..\..\Shared\ContentAccess\ContentAccess\ContentAccess.csproj" />
    <ProjectReference Include="..\..\..\Shared\ContentAccess\ContentAccess.Redis\ContentAccess.Redis.csproj" />
    <ProjectReference Include="..\..\..\EducationContentService\src\EducationContentService.Contracts\EducationContentService.Contracts.csproj" />
    <ProjectReference Include="..\..\..\FileService\src\FileService.Contracts\FileService.Contracts.csproj" />
    <ProjectReference Include="..\..\..\TagService\src\TagService.Contracts\TagService.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Shared\Messaging\RabbitMqMessaging\RabbitMqMessaging.csproj" />
    <ProjectReference Include="..\SearchService.Contracts\SearchService.Contracts.csproj" />
    <ProjectReference Include="..\SearchService.Domain\SearchService.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Database\Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\EducationDocuments\IntegrationEvents\Courses\" />
    <Folder Include="Features\EducationDocuments\IntegrationEvents\Projects\" />
  </ItemGroup>
  
</Project>
